### PR TITLE
Add and submit listing

### PR DESCRIPTION
**Pull request by Sindex42**

### CODE REVIEW

**Comment by Sindex42** [comment]
[Name spaces](https://trello.com/c/WsIgzhVv/5-name-spaces)

**Comment by Sindex42** [comment]
[Space descriptions](https://trello.com/c/rDlyhD42/6-space-descriptions)

**Comment by Sindex42** [comment]
[Price per night](https://trello.com/c/mAAGD48K/7-price-per-night)

**Comment by Sindex42** [comment]
[Price per night](https://trello.com/c/mAAGD48K/7-price-per-night)

**Review by tomlovesgithub — COMMENTED** [review]
gr8 looks good 👍

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
